name: Renovate
on:
  schedule: [{ cron: '0 3 * * *' }]
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovabot/renovate-runner@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
